apiVersion: v2
name: sealed-subchart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: sealed-secrets
  version: 2.8.2
  repository: https://bitnami-labs.github.io/sealed-secrets